### PR TITLE
add support for DataDog events

### PR DESCRIPTION
**Pull request by leedo**
This adds a new `event` method that submits an event to DataDog. Tests were added as well.

### CODE REVIEW

**Comment by chicks-net** [comment]
Is there any reason this is not good enough to merge?

**Comment by finn** [comment]
@binary-com / @jy-binary would love to see this merged. What's the process for getting this PR accepted?

**Comment by tom-binary** [comment]
We'll review the change and aim for a release this week.

@leedo thanks for the contribution!

**Comment by finn** [comment]
@binarytom Thanks for merging! Any timeframe for when this new code / version will make its way up to CPAN? (https://metacpan.org/pod/DataDog::DogStatsd)

**Pull request merged**
